version: "3.11.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "postgres:latest"
    env_file:
      - .env
